### ISSUE TITLE
Synchronization and Integration

### ISSUE THREAD

**Issue by sandroscosta** [fccn/nau-financial-manager#7]
A system sync with the accounting system has to be created. This system sends valid receipt information to the accounting system as gets back a link to a PDF file of the receipt.

A transaction sync has a state, which is the result of the communication with the accounting system. Every time a sync request fails, a retry-count field is incremented.

The format of the information that will be sent to the accounting system is still not clear.

System Sync should defined the following states

* Pending
* Created
* Finished
* Error

### Synchronization State Model

* Receipt
* state
* retry count

### Integration Call:

Content - a json like response or an output of the financial system with an error

**(Possible) States**

* pending -> nothing has been sent to the financial system
* created -> information created on the financial system system
* finished -> received the invoice PDF link.
* error -> something went wrong

## Integration
Integration will be done via *async* [celery](https://docs.celeryq.dev/en/stable/getting-started/introduction.html) pipeline.

**Synchronous or Asynchronous**
We need o use an Asynchronous mode for integrations of creating Receipts on the financial system.
We are going to use Celery for this.

**Signal of Receipt**
Create a job on celery to send information to the financial system.
Celery worker will dispatch the message to the financial system (dispatcher). If an error happens, then it won't retry it.
The retries will be executed by a Django cli command. This command will run for tasks that have returned an error on celery, based on a `cron` based approach.

**Comment by igobranco** [comment]
Closing this old issue,
